Repository FLAME-study/Algorithm-Study, pull requests merged in 2024-08, with the labels that each got.

#4 Feat: 팩토리얼 관련문제 풀이
  KDW/LeetCode/172-factorial-trailing-zeroes.py
Labels: LeetCode, Low, Python

#6 [Feat]브루트포스 문제풀이
  test/bruteforce.py
Labels: Low, Python

#5 [Feat] 브루트포스 문제와 백트래킹 관련문제 풀이
  LHA/baekjoon/n15651.py
  LHA/baekjoon/n6131.py
Labels: Python

#9 8월 첫째주 문제풀이 공유
  KDW/LeetCode/2160.py
Labels: LeetCode, Python

#8 8월 1주차 GCD문제풀이
  gcd.py
  gcd_2.py
Labels: Python

#7 [Feat] 수학 문제풀이 추가
  LHA/baekjoon/n11050.py
  LHA/baekjoon/n5347.py
Labels: BOJ, Python

#13 [Feat]빅오문제
  big_o.py
Labels: BOJ
